#smartthings presentation:device-config:create --yaml --input lan-divoom-deviceConfig.yaml
type: profile
dashboard:
  states:
    - component: main
      capability: switch
      version: 1
      idx: 0
      group: main
      values: [ ]
  actions:
    - component: main
      capability: switch
      version: 1
      idx: 0
      group: main
detailView:
  - component: main
    capability: switch
    version: 1
    values: [ ]
    patch: [ ]
  - component: main
    capability: refresh
    version: 1
    values: [ ]
    patch: [ ]
  - component: switch1
    capability: switch
    version: 1
    values: [ ]
    patch: [ ]
  - component: temperatureMeasurement
    capability: temperatureMeasurement
    version: 1
    values: [ ]
    patch: [ ]
automation:
  conditions:
    - component: main
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: switch1
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: temperatureMeasurement
      capability: temperatureMeasurement
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
  actions:
    - component: main
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: switch1
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: temperatureMeasurement
      capability: temperatureMeasurement
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
presentationId: 9f82b634-c7be-3888-905f-f6047a9197df
manufacturerName: SmartThingsCommunity