#smartthings presentation:device-config:create --yaml --input zigbee-tuya-switch-3-group-deviceConfig.yaml
type: profile
dashboard:
  states:
    - component: main
      capability: switch
      version: 1
      idx: 0
      group: main
      composite: true
      values: [ ]
    - component: switch1
      capability: switch
      version: 1
      idx: 0
      group: switch1
      composite: true      
      values: [ ]
    - component: siwitch2
      capability: switch
      version: 1
      idx: 0
      group: switch2
      composite: true     
      values: [ ]
    - component: switch3
      capability: switch
      version: 1
      idx: 0
      group: switch3
      composite: true      
      values: [ ]
  actions:
    - component: main
      capability: switch
      version: 1
      idx: 0
      group: main
    - component: switch1
      capability: switch
      version: 1
      idx: 0
      group: switch1
    - component: switch2
      capability: switch
      version: 1
      idx: 0
      group: switch2
    - component: switch3
      capability: switch
      version: 1
      idx: 0
      group: switch3
detailView:
  - component: main
    capability: switch
    version: 1
    values: [ ]
    patch: [ ]
  - component: main
    capability: refresh
    version: 1
    values: [ ]
    patch: [ ]
  - component: switch1
    capability: switch
    version: 1
    values: [ ]
    patch: [ ]
  - component: switch2
    capability: switch
    version: 1
    values: [ ]
    patch: [ ]
  - component: switch3
    capability: switch
    version: 1
    values: [ ]
    patch: [ ]
automation:
  conditions:
    - component: main
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: switch1
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: switch2
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: switch3
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
  actions:
    - component: main
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: switch1
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: switch2
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: switch3
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
