#smartthings presentation:device-config:create --yaml --input zigbee-sonoff-button-1-deviceConfig.yaml
mnmn: SmartThingsCommunity
vid: 07b00e93-935a-3703-9b48-706ac1c03b51
version: 0.0.1
type: profile
dashboard:
  states:
    - component: main
      capability: battery
      version: 1
      idx: 0
      group: main
      values: [ ]
  actions:
    - component: button1
      capability: button
      version: 1
      values: [ ]
      patch: [ ]
detailView:
  - component: main
    capability: battery
    version: 1
    values: [ ]
    patch: [ ]
  - component: button1
    capability: button
    version: 1
    values: [ ]
    patch: [ ]
automation:
  conditions:
    - component: button1
      capability: button
      version: 1
      values: [ ]
      patch: [ ]
  actions:
    - component: button1
      capability: button
      version: 1
      values: [ ]
      patch: [ ]
presentationId: 07b00e93-935a-3703-9b48-706ac1c03b51
manufacturerName: SmartThingsCommunity